# Generated by Django 4.2.3 on 2023-08-07 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_alter_product_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_products',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
