# Generated by Django 4.2.3 on 2023-08-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount_of_products',
            name='amount',
            field=models.IntegerField(default=0, help_text='указывать количество', verbose_name='Количество'),
        ),
    ]
